version: 2
updates:
  - package-ecosystem: bun
    directories:
      - /
      - /services/apple-token
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
